server:
  port: ${PORT:${SERVER_PORT:0}}
  
spring:
 data:
   mongodb:
       database: bankclient
       uri: mongodb+srv://sa:root@javabootcamp.p1mwttm.mongodb.net/?retryWrites=true&w=majority

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}