server:
  port: 8088
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/wpretell/Bank-Config-Server.git
          search-paths: config-data
  application:
    name: Bank-Config-Server